hydra:
  run:
    dir: ./.logs/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

artifacts:
    checkpoint:
        use: false
        dirpath: checkpoints
        filename: "{epoch:02d}-{val_loss:.4f}"
        monitor: val_loss
        save_top_k: 3
        every_n_train_steps:
        every_n_epochs: 1
    model:
        path: data/
        name: model
    enable_logger: true
    experiment_name: predict_nt
    mlflow_tracking_uri: "file:./.logs/my-mlflow-logs"
    #mlflow_tracking_uri: "http://gismlops.mlflow"

callbacks:
    model_summary:
        max_depth: 1
    swa:
        use: false
        lrs: 1e-3

data:
    raw_xlsx: "data/raw.xlsx"
    csv_path: "data/out.csv"
    batch_size: 64
    dataloader_num_wokers: 4
    val_size: 0.01
    test_size: 0.99
    max_dataset_length: 0.1
    input_gap: 2000
    prediction_distance: 7000

general:
    seed: 42

model:
    input_size: 3
    prediction_size: 1
    layer_scale: 50

train:
    learning_rate: 1e-2
    num_warmup_steps: 1200
    num_training_steps: 18000
    grad_accum_steps: 4
    accelerator: auto
    #devices:
    #    - 0
    precision: 32
    val_check_interval: 1.0
    overfit_batches: 0
    num_sanity_val_steps: 4
    full_deterministic_mode: true
    benchmark: false
    gradient_clip_val: 1.0
    profiler:
    log_every_n_steps: 256
    detect_anomaly: false
